- hosts: localhost
  gather_facts: false

  tasks:
    - name: Find providers
      find:
        paths: "{{ playbook_dir }}/vars"
        file_type: directory
      register: providers

    - name: Find checks
      find:
        paths: "{{ playbook_dir }}/roles/checks"
        file_type: directory
      register: checks

    - name: Build catalog data
      include_role:
        name: post-metadata
        tasks_from: build_catalog
      vars:
        provider: "{{ item.path | basename }}"
      loop: "{{ providers.files|sort(attribute='path') }}"

    - name: Dump metadata
      import_role:
        name: post-metadata
        tasks_from: dump
